import type { GenreHubConfig } from '../genre-hub.js';

// ─── G. 能力 (abilities) — 10 hub ────────────────────────

export const ABILITIES_CONFIGS: ReadonlyArray<GenreHubConfig> = [
  {
    slug: 'stamina',
    short_ja: '持久力',
    title_ja: '持久力・スタミナが核となる職業',
    description_ja: '長時間の身体活動を維持するスタミナが業務の核心となる職業群。建設・運輸・救急・スポーツ系で求められる中心的な能力。',
    og_eyebrow: 'ABILITY · スタミナ',
    dimension_field: 'abilities_top5',
    dimension_key: 'stamina',
    characteristics_ja: ['長時間の身体活動を維持できる', '体力的負荷の繰り返しに耐性がある', '不規則な勤務にも対応'],
    how_to_develop_ja: ['日常的な有酸素運動', '長時間作業に慣れるトレーニング', '休息と栄養の自己管理'],
  },
  {
    slug: 'physical-strength',
    short_ja: '筋力',
    title_ja: '筋力が必要な職業',
    description_ja: '重量物の運搬・身体を使った作業など、筋力が業務遂行に直結する職業群。建設・運輸・農林・救急系で重要な能力。',
    og_eyebrow: 'ABILITY · 筋力',
    dimension_field: 'abilities_top5',
    dimension_key: 'static_strength',
    characteristics_ja: ['重量物を持ち上げ・運搬できる', '長時間の身体労働に耐える', '瞬発的な力も発揮できる'],
    how_to_develop_ja: ['定期的な筋力トレーニング', '正しい持ち方・動き方の学習', '身体機能の維持習慣'],
  },
  {
    slug: 'manual-dexterity-fine',
    short_ja: '細かい手作業',
    title_ja: '細かい手作業の職業',
    description_ja: '指先の精密な動きや繊細な手技が求められる職業群。歯科衛生士・美容師・職人・組立工等。',
    og_eyebrow: 'ABILITY · 手先の器用さ',
    dimension_field: 'abilities_top5',
    dimension_key: 'manual_dexterity',
    characteristics_ja: ['指先の精密な動きが得意', '繊細な作業を集中して継続できる', '視覚と手の協調性が高い'],
    how_to_develop_ja: ['楽器・手芸など指先を使う趣味', '熟練者の手技を観察し模倣', '反復練習による筋肉記憶'],
  },
  {
    slug: 'visualization',
    short_ja: '空間認識',
    title_ja: '空間認識・モノの見え方が要る職業',
    description_ja: '物体の構造・配置・回転を頭の中で操作できる空間認識力が業務に直結する職業群。建築士・デザイナー・パイロット・外科医等。',
    og_eyebrow: 'ABILITY · 空間認識',
    dimension_field: 'abilities_top5',
    dimension_key: 'visualization',
    characteristics_ja: ['3D 空間を頭の中で操作できる', '図面と実物を相互変換できる', 'パターン認識が早い'],
    how_to_develop_ja: ['3D モデリング・CAD の練習', 'パズル・建築模型などの趣味', '空間認知トレーニングアプリ'],
  },
  {
    slug: 'selective-attention',
    short_ja: '選択的注意',
    title_ja: '集中力・選択的注意が要る職業',
    description_ja: '複数の情報の中から必要なものに注意を集中する力が業務の中心となる職業群。航空管制・トレーダー・救急現場・品質検査等。',
    og_eyebrow: 'ABILITY · 集中',
    dimension_field: 'abilities_top5',
    dimension_key: 'selective_attention',
    characteristics_ja: ['ノイズの中で重要情報に注目できる', '長時間の集中を維持できる', '複数タスクの優先順位を即決'],
    how_to_develop_ja: ['マインドフルネス', 'ノイズ環境での読書練習', '時間管理ツールの活用'],
  },
  {
    slug: 'problem-sensitivity',
    short_ja: '問題察知力',
    title_ja: '問題察知力が要る職業',
    description_ja: '不具合・予兆・違和感を早期に察知する力が業務の核心となる職業群。整備士・検査技師・看護師・治安維持等。',
    og_eyebrow: 'ABILITY · 察知',
    dimension_field: 'abilities_top5',
    dimension_key: 'problem_sensitivity',
    characteristics_ja: ['わずかな違和感を見逃さない', '予兆段階での介入判断', '経験パターンとの照合が速い'],
    how_to_develop_ja: ['熟練者の「気づき」を言語化', '点検チェックリストの習慣化', 'ケース蓄積による直感のブラッシュアップ'],
  },
  {
    slug: 'oral-comprehension',
    short_ja: '言語理解',
    title_ja: '言語理解力が要る職業',
    description_ja: '話される言葉の意味を正確に把握する力が業務に直結する職業群。通訳・カウンセラー・教師・営業等。',
    og_eyebrow: 'ABILITY · 言語理解',
    dimension_field: 'abilities_top5',
    dimension_key: 'oral_comprehension',
    characteristics_ja: ['複雑な説明を即座に理解', '言葉のニュアンスを読み取る', '専門用語と平易な表現の橋渡し'],
    how_to_develop_ja: ['多様な分野の本を読む', '発言を要約する練習', '異文化・異年代との会話機会'],
  },
  {
    slug: 'inductive-reasoning',
    short_ja: '帰納的推論',
    title_ja: '帰納的推論が要る職業',
    description_ja: '個別の事例から一般法則を導く帰納的思考が業務の中心となる職業群。研究者・データサイエンティスト・診断医・刑事等。',
    og_eyebrow: 'ABILITY · 推論',
    dimension_field: 'abilities_top5',
    dimension_key: 'inductive_reasoning',
    characteristics_ja: ['複数事例からパターンを発見', '仮説生成と検証のサイクル', '不完全情報から結論を導く'],
    how_to_develop_ja: ['ベイズ推論・統計学の基礎', '推理小説・科学誌の読書', 'データ分析の実践'],
  },
  {
    slug: 'deductive-reasoning',
    short_ja: '演繹的推論',
    title_ja: '演繹的推論が要る職業',
    description_ja: '一般原則やルールから個別事例の結論を導く演繹的思考が業務の核心となる職業群。弁護士・公認会計士・システムエンジニア・医師等。',
    og_eyebrow: 'ABILITY · 演繹',
    dimension_field: 'abilities_top5',
    dimension_key: 'deductive_reasoning',
    characteristics_ja: ['ルール体系から答えを導ける', '前提条件の妥当性を検証できる', '論理的な反証可能性を意識する'],
    how_to_develop_ja: ['形式論理学・数学の学習', '法律・契約書の読解', 'プログラミングによるロジック構築'],
  },
  {
    slug: 'oral-expression',
    short_ja: '発話表現',
    title_ja: '発話表現力が要る職業',
    description_ja: '考えを言葉で的確に伝える発話表現力が業務の中心となる職業群。営業・教師・カウンセラー・士業・接客サービス等。',
    og_eyebrow: 'ABILITY · 発話',
    dimension_field: 'abilities_top5',
    dimension_key: 'oral_expression',
    characteristics_ja: ['複雑な内容を平易に説明できる', '相手の理解度に応じて語り方を変えられる', '緊張下でも論理を保てる'],
    how_to_develop_ja: ['プレゼン・スピーチの練習', '相手別に説明シナリオを書く', 'その場の議論・ディベート参加'],
  },
];
