import type { GenreHubConfig } from '../genre-hub.js';

// ─── H. 知識 (knowledge) — 10 hub ────────────────────────

export const KNOWLEDGE_CONFIGS: ReadonlyArray<GenreHubConfig> = [
  {
    slug: 'production-processing',
    short_ja: '生産・加工',
    title_ja: '生産・加工の知識を活かす職業',
    description_ja: '原料・工程・品質管理など、モノづくりの一連知識が業務に直結する職業群。製造業全般、食品加工、化学プラント等。',
    og_eyebrow: 'KNOWLEDGE · 生産加工',
    dimension_field: 'knowledge_top5',
    dimension_key: 'production_processing',
    characteristics_ja: ['工程と品質の関係を把握', '原料特性と加工条件を理解', '安全と効率を両立できる'],
    how_to_develop_ja: ['現場での OJT', '製造業向け資格 (技能士等)', '工程改善 (カイゼン) の事例研究'],
  },
  {
    slug: 'customer-service',
    short_ja: '顧客サービス',
    title_ja: '顧客サービス知識を活かす職業',
    description_ja: '顧客のニーズ把握・問題解決・関係構築の知識が業務の核心となる職業群。販売・接客・営業・コールセンター等。',
    og_eyebrow: 'KNOWLEDGE · 顧客サービス',
    dimension_field: 'knowledge_top5',
    dimension_key: 'customer_personal_service',
    characteristics_ja: ['顧客の本音を引き出せる', 'クレーム対応の型を持つ', 'リピート関係を構築する'],
    how_to_develop_ja: ['CS 関連書籍の読書', 'ロールプレイ研修', '優れた接客の観察と分析'],
  },
  {
    slug: 'mechanical-knowledge',
    short_ja: '機械',
    title_ja: '機械知識を活かす職業',
    description_ja: '機械の設計・動作原理・故障パターンの知識が業務の中心となる職業群。整備士・技術者・製造現場・操縦系等。',
    og_eyebrow: 'KNOWLEDGE · 機械',
    dimension_field: 'knowledge_top5',
    dimension_key: 'mechanical',
    characteristics_ja: ['機械の構造を理解', '故障診断ができる', '工具と治具を使いこなす'],
    how_to_develop_ja: ['機械整備の資格取得', '実機を分解・組立する経験', '機械工学の基礎知識'],
  },
  {
    slug: 'medical-knowledge',
    short_ja: '医学・生物学',
    title_ja: '医学・生物学知識を活かす職業',
    description_ja: '人体・疾病・治療法の知識が業務に直結する職業群。医師・看護師・薬剤師・臨床検査技師等。',
    og_eyebrow: 'KNOWLEDGE · 医学',
    dimension_field: 'knowledge_top5',
    dimension_key: 'medicine_dentistry',
    characteristics_ja: ['人体構造と機能を理解', '症状から疾患を推論', '治療法の長短を比較'],
    how_to_develop_ja: ['医学部・看護学校・薬学部', '国家資格取得', '継続的な医学知識のアップデート'],
  },
  {
    slug: 'mathematics-knowledge',
    short_ja: '数学',
    title_ja: '数学知識を活かす職業',
    description_ja: '統計・微積分・線形代数など数学的知識が業務の中心となる職業群。研究者・エンジニア・金融・データサイエンティスト等。',
    og_eyebrow: 'KNOWLEDGE · 数学',
    dimension_field: 'knowledge_top5',
    dimension_key: 'mathematics_kn',
    characteristics_ja: ['数式と現象の関係を把握', 'データから法則を抽出', '不確実性を定量的に扱う'],
    how_to_develop_ja: ['大学レベルの数学を学習', '統計検定・データ分析関連資格', '実務でのデータ活用'],
  },
  {
    slug: 'psychology-knowledge',
    short_ja: '心理学',
    title_ja: '心理学知識を活かす職業',
    description_ja: '人間の認知・感情・行動に関する心理学的知識が業務の中心となる職業群。カウンセラー・教師・人事・営業・看護等。',
    og_eyebrow: 'KNOWLEDGE · 心理学',
    dimension_field: 'knowledge_top5',
    dimension_key: 'psychology',
    characteristics_ja: ['行動の背景にある動機を読み取る', '集団心理と個人心理の違いを意識', 'バイアスを認識して判断する'],
    how_to_develop_ja: ['心理学の基礎書籍', '臨床・産業心理学関連資格', '実務での観察・記録の蓄積'],
  },
  {
    slug: 'law-government-knowledge',
    short_ja: '法律・行政',
    title_ja: '法律・行政知識を活かす職業',
    description_ja: '法令・行政手続・規制の知識が業務の中心となる職業群。弁護士・司法書士・行政書士・公務員・コンプライアンス担当等。',
    og_eyebrow: 'KNOWLEDGE · 法律',
    dimension_field: 'knowledge_top5',
    dimension_key: 'law_government',
    characteristics_ja: ['法令の条文と判例を読解できる', '手続きの順序と期限を厳守', '規制と現実の乖離を埋める'],
    how_to_develop_ja: ['法学部・法科大学院での学習', '士業国家資格の取得', '判例研究・実務経験の蓄積'],
  },
  {
    slug: 'computers-electronics-knowledge',
    short_ja: 'IT・電子',
    title_ja: 'IT・電子工学知識を活かす職業',
    description_ja: 'コンピューター・ネットワーク・電子工学の知識が業務に直結する職業群。エンジニア・SE・データサイエンティスト・組込み技術者等。',
    og_eyebrow: 'KNOWLEDGE · IT',
    dimension_field: 'knowledge_top5',
    dimension_key: 'computers_electronics',
    characteristics_ja: ['ハード・ソフトの全体像を把握', '抽象化と具体実装を行き来', '新技術を継続的に習得'],
    how_to_develop_ja: ['情報系学部・専門学校', '資格 (情報処理・ベンダー系)', 'OSS / 個人プロジェクトでの実装経験'],
  },
  {
    slug: 'japanese-language-knowledge',
    short_ja: '国語・日本語',
    title_ja: '国語・日本語知識を活かす職業',
    description_ja: '日本語の文法・語彙・文章構成の知識が業務に直結する職業群。教師・編集者・ライター・通訳・士業の文書業務等。',
    og_eyebrow: 'KNOWLEDGE · 国語',
    dimension_field: 'knowledge_top5',
    dimension_key: 'japanese_language',
    characteristics_ja: ['正確な文章を書き分けられる', '相手と場面に応じた語彙選択', '推敲・校正の精度が高い'],
    how_to_develop_ja: ['古典・近代文学の読書', '校正・編集の実務訓練', '専門領域の文章スタイル習得'],
  },
  {
    slug: 'sales-marketing-knowledge',
    short_ja: '営業・販売',
    title_ja: '営業・販売の知識を活かす職業',
    description_ja: '商品・市場・顧客行動・販売手法の知識が業務に直結する職業群。営業職・マーケター・店長・販売員・ECディレクター等。',
    og_eyebrow: 'KNOWLEDGE · 営業',
    dimension_field: 'knowledge_top5',
    dimension_key: 'sales_marketing',
    characteristics_ja: ['顧客課題と商品価値を結びつける', '購買心理と市場動向を読む', '数字とストーリーを両立させる'],
    how_to_develop_ja: ['営業・マーケティング関連資格', '優れた営業の同行・観察', 'デジタルマーケティング実践'],
  },
];
