/**
 * src/templates/Compare.ts — HTML / JSON-LD for the 12 /compare/[pair]
 * hub pages + /compare index.
 *
 * Extracted from src/views/compare-hub.ts on 2026-05-14 (Phase D #6 per
 * docs/architecture.md §8 row 12 "data is view, HTML is template").
 *
 * Same template pattern as Phase D #2 (SkillHub) + #3 (InterestHub):
 * renderRelatedCompares now takes allMeta as a parameter; templates per
 * scripts/check-architecture.cjs cannot import view-layer values.
 */
import type { CompareSlug, CompareMeta } from '../views/compare-meta.js';
import type { CompareSide, CompareResult } from '../views/compare-hub.js';
import { escapeHtml, type SafeHtml } from '../lib/safe-html.js';
import { riskClass } from '../lib/risk.js';
import { CONTENT_DATE } from '../lib/_content-date.js';
import { occupationPath } from '../lib/urls.js';

export { escapeHtml };
export { renderFaqSection as renderFaqHtml } from './FaqSection.js';

export function renderCompareHero(a: CompareSide, b: CompareSide): SafeHtml {
  const aBand = riskClass(a.ai_risk);
  const bBand = riskClass(b.ai_risk);
  const aRiskStr = a.ai_risk !== null ? `${a.ai_risk}/10` : '—';
  const bRiskStr = b.ai_risk !== null ? `${b.ai_risk}/10` : '—';
  return (
    `<div class="versus-hero">` +
    `<div class="vh-side">` +
    `<a href="${occupationPath(a.id)}" class="vh-name">${escapeHtml(a.name_ja)}</a>` +
    `<span class="risk-pill ${aBand}">AI 影響 ${escapeHtml(aRiskStr)}</span>` +
    (a.sector_ja ? `<span class="vh-sector">${escapeHtml(a.sector_ja)}</span>` : '') +
    `</div>` +
    `<div class="vh-vs"><span>VS</span></div>` +
    `<div class="vh-side">` +
    `<a href="${occupationPath(b.id)}" class="vh-name">${escapeHtml(b.name_ja)}</a>` +
    `<span class="risk-pill ${bBand}">AI 影響 ${escapeHtml(bRiskStr)}</span>` +
    (b.sector_ja ? `<span class="vh-sector">${escapeHtml(b.sector_ja)}</span>` : '') +
    `</div>` +
    `</div>`
  ) as SafeHtml;
}

export function renderCompareTable(rows: CompareResult['rows'], aName: string, bName: string): SafeHtml {
  const headers =
    `<thead><tr>` +
    `<th>項目</th>` +
    `<th>${escapeHtml(aName)}</th>` +
    `<th>${escapeHtml(bName)}</th>` +
    `<th class="ct-note">差分</th>` +
    `</tr></thead>`;
  const body = rows
    .map(
      (r) =>
        `<tr>` +
        `<th scope="row">${escapeHtml(r.label)}</th>` +
        `<td>${escapeHtml(r.a_val)}</td>` +
        `<td>${escapeHtml(r.b_val)}</td>` +
        `<td class="ct-note">${escapeHtml(r.note)}</td>` +
        `</tr>`,
    )
    .join('');
  return `<table class="compare-table">${headers}<tbody>${body}</tbody></table>` as SafeHtml;
}

export function renderTopSkillsCompare(a: CompareSide, b: CompareSide): SafeHtml {
  function skillList(side: CompareSide): string {
    if (side.top_skills.length === 0) return '<p class="ts-empty">—</p>';
    const lis = side.top_skills
      .map(
        (s) =>
          `<li><span class="ts-name">${escapeHtml(s.label_ja)}</span><span class="ts-score">${s.score.toFixed(2)}</span></li>`,
      )
      .join('');
    return `<ol class="ts-list">${lis}</ol>`;
  }
  return (
    `<div class="topskills-compare">` +
    `<div class="tsc-side">` +
    `<h3>${escapeHtml(a.name_ja)} の主要スキル</h3>` +
    skillList(a) +
    `</div>` +
    `<div class="tsc-side">` +
    `<h3>${escapeHtml(b.name_ja)} の主要スキル</h3>` +
    skillList(b) +
    `</div>` +
    `</div>`
  ) as SafeHtml;
}

/**
 * Phase D #6 (2026-05-14) signature change: `allMeta` now passed in.
 * Previous version read COMPARE_META from view layer.
 */
export function renderRelatedCompares(
  currentSlug: CompareSlug,
  allMeta: ReadonlyArray<CompareMeta>,
): SafeHtml {
  const items = allMeta
    .filter((m) => m.slug !== currentSlug)
    .slice(0, 6)
    .map(
      (m) =>
        `<li><a href="/compare/${m.slug}">` +
        `<span class="rc-title">${escapeHtml(m.title_ja)}</span>` +
        `</a></li>`,
    )
    .join('');
  return `<ul class="related-compares">${items}</ul>` as SafeHtml;
}

// ─── JSON-LD ───────────────────────────────────────────────────

const SITE = 'https://mirai-shigoto.com';
const DATE_PUBLISHED = '2026-05-09';
const DATE_MODIFIED = CONTENT_DATE;  // Generated by build:data — see Ranking.ts

export function renderJsonLd(
  canonical: string,
  meta: CompareMeta,
  a: CompareSide,
  b: CompareSide,
  description: string,
  faqItems: ReadonlyArray<readonly [string, string]> | null,
): string {
  const graph: unknown[] = [
    {
      '@type': 'WebPage',
      '@id': `${canonical}#webpage`,
      url: canonical,
      name: meta.title_ja,
      description,
      isPartOf: { '@id': `${SITE}/#website` },
      inLanguage: 'ja',
      datePublished: DATE_PUBLISHED,
      dateModified: DATE_MODIFIED,
      publisher: { '@id': `${SITE}/#organization` },
      breadcrumb: { '@id': `${canonical}#breadcrumb` },
      speakable: {
        '@type': 'SpeakableSpecification',
        cssSelector: ['.ai-fact', '.intro', '.compare-table'],
      },
    },
    {
      '@type': 'Article',
      '@id': `${canonical}#article`,
      headline: meta.title_ja,
      description,
      url: canonical,
      image: `${SITE}/api/og?compare=${meta.slug}`,
      datePublished: DATE_PUBLISHED,
      dateModified: DATE_MODIFIED,
      author: { '@id': `${SITE}/#organization` },
      publisher: { '@id': `${SITE}/#organization` },
      inLanguage: 'ja',
      mainEntityOfPage: { '@id': `${canonical}#webpage` },
      isPartOf: { '@id': `${canonical}#webpage` },
      articleSection: '比較',
      about: [
        { '@type': 'Thing', name: a.name_ja, url: `${SITE}${occupationPath(a.id)}` },
        { '@type': 'Thing', name: b.name_ja, url: `${SITE}${occupationPath(b.id)}` },
      ],
    },
    {
      '@type': 'BreadcrumbList',
      '@id': `${canonical}#breadcrumb`,
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: '未来の仕事', item: `${SITE}/` },
        { '@type': 'ListItem', position: 2, name: '職業を比較する', item: `${SITE}/compare` },
        { '@type': 'ListItem', position: 3, name: meta.title_ja, item: canonical },
      ],
    },
  ];

  if (faqItems && faqItems.length > 0) {
    graph.push({
      '@type': 'FAQPage',
      '@id': `${canonical}#faq`,
      mainEntity: faqItems.map(([q, ans]) => ({
        '@type': 'Question',
        name: q,
        acceptedAnswer: { '@type': 'Answer', text: ans },
      })),
    });
  }

  return JSON.stringify({ '@context': 'https://schema.org', '@graph': graph }, null, 2);
}

// ─── compare/index hub-card renderer (Phase D audit #8 2026-05-14) ────

export interface CompareHubCard {
  readonly slug: string;
  readonly title_ja: string;
  readonly a_name: string;
  readonly a_risk: number | null;
  readonly b_name: string;
  readonly b_risk: number | null;
  readonly description_ja: string;
  /** /compare hub double-layer (2026-06-04); true = big card, false = compact chip */
  readonly featured?: boolean;
}

function compareRiskClass(score: number | null): 'low' | 'mid' | 'high' {
  if (score === null) return 'mid';
  if (score <= 3) return 'low';
  if (score <= 6) return 'mid';
  return 'high';
}

/**
 * 2026-06-04 双層改造: 説明付きの大カード。/compare hub で featured ペアのみに使う。
 * v2 (2026-06-04): タイトルを大きく + ペアを A 行 / vs / B 行 の縦積みに分割
 * (横一列は日本語の長い職業名で省略されて読めなかった)。
 */
export function renderFeaturedCompareCards(cards: ReadonlyArray<CompareHubCard>): SafeHtml {
  return cards.map((c) => {
    const aBand = compareRiskClass(c.a_risk);
    const bBand = compareRiskClass(c.b_risk);
    const aRiskStr = c.a_risk !== null ? `${c.a_risk}/10` : '—';
    const bRiskStr = c.b_risk !== null ? `${c.b_risk}/10` : '—';
    return (
      `<li><a href="/compare/${c.slug}">` +
      `<span class="cci-title">${escapeHtml(c.title_ja)}</span>` +
      `<span class="cci-pair">` +
      `<span class="cci-side">` +
      `<span class="cci-name">${escapeHtml(c.a_name)}</span>` +
      `<span class="risk-pill ${aBand}">${escapeHtml(aRiskStr)}</span>` +
      `</span>` +
      `<span class="cci-vs-row" aria-hidden="true">vs</span>` +
      `<span class="cci-side">` +
      `<span class="cci-name">${escapeHtml(c.b_name)}</span>` +
      `<span class="risk-pill ${bBand}">${escapeHtml(bRiskStr)}</span>` +
      `</span>` +
      `</span>` +
      `<span class="cci-desc">${escapeHtml(c.description_ja.length > 80 ? c.description_ja.slice(0, 80) + '…' : c.description_ja)}</span>` +
      `</a></li>`
    );
  }).join('') as SafeHtml;
}

/**
 * 2026-06-04 双層改造: タイトル + 双方の名前 + 両 risk pill のみのコンパクト chip。
 * 説明文を出さないので、20 ペアでも視覚的に圧迫しない。
 */
export function renderCompactCompareCards(cards: ReadonlyArray<CompareHubCard>): SafeHtml {
  return cards.map((c) => {
    const aBand = compareRiskClass(c.a_risk);
    const bBand = compareRiskClass(c.b_risk);
    const aRiskStr = c.a_risk !== null ? `${c.a_risk}/10` : '—';
    const bRiskStr = c.b_risk !== null ? `${c.b_risk}/10` : '—';
    return (
      `<li><a href="/compare/${c.slug}">` +
      `<span class="ccq-title">${escapeHtml(c.title_ja)}</span>` +
      `<span class="ccq-pair">` +
      `<span class="ccq-name">${escapeHtml(c.a_name)}</span>` +
      `<span class="risk-pill ${aBand}">${escapeHtml(aRiskStr)}</span>` +
      `<span class="ccq-vs">vs</span>` +
      `<span class="ccq-name">${escapeHtml(c.b_name)}</span>` +
      `<span class="risk-pill ${bBand}">${escapeHtml(bRiskStr)}</span>` +
      `</span>` +
      `</a></li>`
    );
  }).join('') as SafeHtml;
}

export function renderHubJsonLd(): string {
  const canonical = `${SITE}/compare`;
  const seoDesc =
    '日本の代表的な職業同士を side-by-side で比較。AI 影響度・年収・労働条件・必要スキルを並べて意思決定の助けに。';
  return JSON.stringify(
    {
      '@context': 'https://schema.org',
      '@graph': [
        {
          '@type': 'WebPage',
          '@id': `${canonical}#webpage`,
          url: canonical,
          name: '職業を比較する',
          description: seoDesc,
          isPartOf: { '@id': `${SITE}/#website` },
          inLanguage: 'ja',
          datePublished: DATE_PUBLISHED,
          dateModified: DATE_MODIFIED,
          publisher: { '@id': `${SITE}/#organization` },
          breadcrumb: { '@id': `${canonical}#breadcrumb` },
        },
        {
          '@type': 'BreadcrumbList',
          '@id': `${canonical}#breadcrumb`,
          itemListElement: [
            { '@type': 'ListItem', position: 1, name: '未来の仕事', item: `${SITE}/` },
            { '@type': 'ListItem', position: 2, name: '職業を比較する', item: canonical },
          ],
        },
      ],
    },
    null,
    2,
  );
}
