/**
 * src/pages/_index-bindings.ts — fs-read helpers for the homepage.
 *
 * After the BaseLayout migration (2026-05-18, RA-??), the homepage no longer
 * carries its own `<head>` / `<nav>` / `<footer>` / cookie banner / analytics.
 * BaseLayout owns all of those — env-driven (single source of truth) instead
 * of the previous duplicate hardcoding (GA4 ID `G-GLDNBDPF13`, X Pixel
 * `rC3xs`, Meta Pixel `1476745404149398` had been pasted twice).
 *
 * The three files below hold what's left of the homepage:
 *   • index-source.html — the body fragment (just `<div id="wrapper">…</div>`).
 *   • _index-json-ld.json — the JSON-LD `@graph` schema (Organization +
 *     WebSite + Dataset + ItemList + FAQPage). Slotted into BaseLayout's
 *     `jsonLd` slot so AI search engines (ChatGPT, Claude, Perplexity,
 *     Gemini) still pick it up.
 *   • _index-inline.js — the ~1880 lines of home-specific JS (treemap
 *     canvas + tooltip + mobile drawer + I18N + share buttons). Imported
 *     by `index.astro` as a Vite `?url` asset so it ships as a hashed,
 *     deferred file instead of inline HTML. Runtime copy that needs the
 *     occupation count derives it from loaded data or page meta instead of
 *     this build-time placeholder pass.
 *
 * Architecture-doc exception (§3.1): fs reads in page-layer code. Mirrors
 * the existing _map-css.ts pattern — at build time only.
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { loadGeoFacts } from '@/page-data/geo-facts-loader';
import { bindHomeFacts } from '@/site/home-facts-render';

// Generated by src/site/geo-build.ts from the active score batch and treemap
// projection. Keep attribution ownership there; this binding only reads it.
const ROOT = process.cwd();
const SRC = join(ROOT, 'src');
const PAGES = join(SRC, 'pages');
const HOME_FACTS = loadGeoFacts();

export const HOME_BODY_HTML: string = bindHomeFacts(readFileSync(
  join(SRC, 'index-source.html'),
  'utf-8',
), HOME_FACTS);

export const HOME_JSON_LD: string = readFileSync(
  join(PAGES, '_index-json-ld.json'),
  'utf-8',
).replaceAll('__OCCUPATION_COUNT_SCORED__', String(HOME_FACTS.occupationCount));
